#!/usr/bin/env sh

# This should be run on master, ensuring all upstream updates are pulled in.
# This script will re-generate and commit the CHANGELOG.md file, tag HEAD
# with the version you specify, push your changes and tag to origin, and
# create a release on Github using the new tag with the message you specify.
#
# Example: ./scripts/release v0.0.0 "Release Notes Message ..."

set -ex
rm -f .git/RELEASE_EDITMSG
touch .git/RELEASE_EDITMSG
echo "${1}\n\n${@}" >> .git/RELEASE_EDITMSG
git tag -s ${1} -F .git/RELEASE_EDITMSG
git push --tags
github_changelog_generator --issue-line-labels="ALL" --release-url="https://github.com/xentek/pikaq/releases/tag/%s"
git commit CHANGELOG.md -m "updates changelog for ${1}"
git push origin master
hub release create -f .git/RELEASE_EDITMSG ${1}

# vim: set ft=sh
