#!/usr/bin/env sh
set -ex

# This script assumes you already have a proper go environment set up.

if which golint > /dev/null; then
  echo "golint alrady installed"
else
  go get -u github.com/x/lint/golint
fi

if which goveralls > /dev/null; then
  echo "goveralls alrady installed"
else
  go get -u github.com/mattn/goveralls
fi

# vim: set ft=sh
