#!/usr/bin/env sh
set -ex

# This script assumes you already have a proper go environment set up.

if which golint > /dev/null; then
  echo "golint alrady installed"
else
  go get -u github.com/golang/lint/golint
fi

if which goveralls > /dev/null; then
  echo "goveralls alrady installed"
else
  go get -u github.com/mattn/goveralls
fi

if [ "$TRAVIS" != "true" ]; then
  if which gem > /dev/null; then
    gem install github_changelog_generator --no-doc
  else
    echo "gem comand not found, skipping installation of github_changelog_generator"
  fi
fi

# vim: set ft=sh
