#!/usr/bin/env sh
set -ex

# This script assumes you already have a proper go environment set up.

if which golint > /dev/null; then
  echo "golint alrady installed"
else
  go get -u golang.org/x/lint/golint
fi

# vim: set ft=sh
